const T=[["normal","一般","#a8a79f"],["fighting","格斗","#d56723"],["flying","飞行","#6f93ff"],["poison","毒","#9f47d2"],["ground","地面","#c8a14d"],["rock","岩石","#b49b3d"],["bug","虫","#8fa51a"],["ghost","幽灵","#6453a3"],["steel","钢","#8a8aa4"],["fire","火","#ee8130"],["water","水","#6390f0"],["grass","草","#7ac74c"],["electric","电","#f7d02c"],["psychic","超能力","#f95587"],["ice","冰","#96d9d6"],["dragon","龙","#6f35fc"],["dark","恶","#705746"],["fairy","妖精","#d685ad"]].map(([k,l,c])=>({k,l,c}));
const C={normal:{rock:.5,ghost:0,steel:.5},fighting:{normal:2,flying:.5,poison:.5,rock:2,bug:.5,ghost:0,steel:2,psychic:.5,ice:2,dark:2,fairy:.5},flying:{fighting:2,rock:.5,bug:2,steel:.5,grass:2,electric:.5},poison:{poison:.5,ground:.5,rock:.5,ghost:.5,steel:0,grass:2,fairy:2},ground:{flying:0,poison:2,rock:2,bug:.5,steel:2,fire:2,grass:.5,electric:2},rock:{fighting:.5,flying:2,ground:.5,bug:2,steel:.5,fire:2,ice:2},bug:{fighting:.5,flying:.5,poison:.5,ghost:.5,steel:.5,fire:.5,grass:2,psychic:2,dark:2,fairy:.5},ghost:{normal:0,ghost:2,psychic:2,dark:.5},steel:{rock:2,steel:.5,fire:.5,water:.5,electric:.5,ice:2,fairy:2},fire:{rock:.5,bug:2,steel:2,fire:.5,water:.5,grass:2,ice:2,dragon:.5},water:{ground:2,rock:2,fire:2,water:.5,grass:.5,dragon:.5},grass:{flying:.5,poison:.5,ground:2,rock:2,bug:.5,steel:.5,fire:.5,water:2,grass:.5,dragon:.5},electric:{flying:2,ground:0,water:2,grass:.5,electric:.5,dragon:.5},psychic:{fighting:2,poison:2,steel:.5,psychic:.5,dark:0},ice:{flying:2,ground:2,steel:.5,fire:.5,water:.5,grass:2,ice:.5,dragon:2},dragon:{steel:.5,dragon:2,fairy:0},dark:{fighting:.5,ghost:2,psychic:2,dark:.5,fairy:.5},fairy:{fighting:2,poison:.5,steel:.5,fire:.5,dragon:2,dark:2,bug:.5}};
const O=[4,2,1,.5,.25,0],K="poke-type-theme",S={m:"defense",s:[],t:gt(),n:true};
const E={g:document.getElementById("type-grid"),st:document.getElementById("selection-title"),sl:document.getElementById("selection-limit"),rt:document.getElementById("results-title"),rp:document.getElementById("results-panel"),sm:document.getElementById("status-message"),r:document.getElementById("reset-button"),nt:document.getElementById("neutral-toggle"),mb:[...document.querySelectorAll(".mode-button")],tb:[...document.querySelectorAll(".theme-button")]};
function gt(){try{return localStorage.getItem(K)==="dark"?"dark":"light";}catch{return"light"}}
function at(t){S.t=t;document.documentElement.dataset.theme=t;E.tb.forEach(b=>{const a=b.dataset.theme===t;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",a?"true":"false")});try{localStorage.setItem(K,t)}catch{}}
const M=k=>T.find(t=>t.k===k);
function tc(h){const g=f=>{const v=parseInt(f.slice(1),16),n=[v>>16&255,v>>8&255,v&255].map(x=>{x/=255;return x<=.03928?x/12.92:((x+.055)/1.055)**2.4});return .2126*n[0]+.7152*n[1]+.0722*n[2]},c=(a,b)=>{const x=g(a),y=g(b),m=Math.max(x,y),n=Math.min(x,y);return (m+.05)/(n+.05)},d="#231f18",l="#fffaf2";return c(h,d)>=c(h,l)?d:l}
const ef=(a,d)=>C[a][d]??1,cf=(a,d)=>d.reduce((p,x)=>p*ef(a,x),1);
const mt=v=>v===.25?"1/4":v===.5?"1/2":`${v}x`;
const mm=v=>v===.25||v===.5?`<span class="fraction" aria-label="${mt(v)} 倍"><span class="fraction__top">1</span><span class="fraction__bar"></span><span class="fraction__bottom">${v===.25?4:2}</span></span>`:`<span class="multiplier-text">${mt(v)}</span>`;
const chip=k=>{const t=M(k);return `<span class="result-chip" style="background:${t.c};color:${tc(t.c)};">${t.l}</span>`};
const duo=a=>a.length<2?chip(a[0]):`<span class="combo-chip">${a.map(k=>{const t=M(k);return `<span class="combo-chip__part" style="background:${t.c};color:${tc(t.c)};">${t.l}</span>`}).join("")}</span>`;
function rb(){const m=S.m==="defense"?2:1;E.sl.textContent=`最多 ${m} 个`;E.g.innerHTML=T.map(t=>`<button class="type-button${S.s.includes(t.k)?" is-selected":""}" type="button" data-type="${t.k}" aria-pressed="${S.s.includes(t.k)}" style="background:${t.c};color:${tc(t.c)};"><span class="type-button__name">${t.l}</span></button>`).join("")}
function rm(){E.st.textContent=S.m==="defense"?"选择防守方属性":"选择攻击方属性";E.mb.forEach(b=>{const a=b.dataset.mode===S.m;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",a?"true":"false")});E.nt.classList.toggle("is-active",S.n);E.nt.setAttribute("aria-pressed",S.n?"true":"false");E.nt.textContent=S.n?"隐藏 1x 属性":"显示 1x 属性"}
function db(){const b=new Map(O.map(v=>[v,[]]));T.forEach(t=>b.get(cf(t.k,S.s)).push(t.k));return b}
function ab(){const b=new Map(O.map(v=>[v,{s:[],d:[]}])),a=S.s[0];T.forEach(t=>b.get(cf(a,[t.k])).s.push(t.k));for(let i=0;i<T.length;i+=1)for(let j=i+1;j<T.length;j+=1){const c=[T[i].k,T[j].k];b.get(cf(a,c)).d.push(c)}return b}
const row=(l,c,b)=>`<section class="result-row"><div class="result-row__head"><span class="multiplier-badge">${l}</span>${c||""}</div><div class="result-row__body">${b}</div></section>`;
function re(){E.rt.textContent="请选择属性";E.rp.innerHTML='<div class="empty-state">请选择属性</div>'}
function rd(){E.rt.textContent=S.s.map(k=>M(k).l).join(" / ");const b=db();E.rp.innerHTML=O.filter(v=>S.n||v!==1).map(v=>{const i=b.get(v);return i.length?row(mm(v),"",`<div class="chips-wrap">${i.map(chip).join("")}</div>`):""}).join("")}
function ra(){E.rt.textContent=M(S.s[0]).l;const b=ab();E.rp.innerHTML=O.filter(v=>S.n||v!==1).map(v=>{const g=b.get(v);if(!g.s.length&&!g.d.length)return"";const p=[];if(g.s.length)p.push(`<div class="subgroup"><p class="subgroup__title">单属性 · ${g.s.length}</p><div class="chips-wrap">${g.s.map(chip).join("")}</div></div>`);if(g.d.length)p.push(`<div class="subgroup"><p class="subgroup__title">双属性 · ${g.d.length}</p><div class="chips-wrap">${g.d.map(duo).join("")}</div></div>`);return row(mm(v),"",p.join(""))}).join("")}
function rr(){if(!S.s.length)return re();S.m==="defense"?rd():ra()}
function an(){E.sm.textContent=!S.s.length?"请选择属性":`${S.m==="defense"?"防守方":"攻击方"}：${S.s.map(k=>M(k).l).join(" / ")}，${S.n?"显示":"隐藏"} 1x 属性`}
function render(){rm();rb();rr();an()}
function pick(k){if(S.m==="defense"){if(S.s.includes(k))S.s=S.s.filter(x=>x!==k);else if(S.s.length<2)S.s=[...S.s,k];else S.s=[k]}else S.s=S.s[0]===k?[]:[k];render()}
E.g.addEventListener("click",e=>{const b=e.target.closest("[data-type]");if(b)pick(b.dataset.type)});
E.mb.forEach(b=>b.addEventListener("click",()=>{if(S.m!==b.dataset.mode){S.m=b.dataset.mode;S.s=[];render()}}));
E.tb.forEach(b=>b.addEventListener("click",()=>at(b.dataset.theme)));
E.nt.addEventListener("click",()=>{S.n=!S.n;render()});
E.r.addEventListener("click",()=>{S.s=[];render()});
at(S.t);
render()
